### ISSUE TITLE
WHITEBOX - opening a door

### ISSUE THREAD

**Issue by TiceShark** [WindowsVista42/UNT_4430_Project#8]

**Comment by WindowsVista42** [comment]
Provide a way for the player to open a door. Preferably, the player can click on the door then the door will change to an open position and the player can walk through. Don't worry about animations for now, just get the door to change to an open position.

We are working in a first-person environment, so a possible good starting point is using the first-person example project that Unreal Engine provides and working from there.

**Comment by TiceShark** [comment]
Modified door based on UE4.27 Tutorial Documentation
Current interaction is automatic fast open when in proximity, and slow close when stepping away from door.

Animation is slightly buggy; door will need to be replaced with actual model.
